services:
    tasket:
        image: ghcr.io/nimueller/tasket:latest
        restart: unless-stopped
        ports:
            - "8080:8080"
        environment:
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
            POSTGRES_DB: ${POSTGRES_DB:-tasket}
            JWT_SECRET: ${JWT_SECRET:-secret}
    postgres:
        image: postgres
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-tasket}
            POSTGRES_USER: ${POSTGRES_PASSWORD:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
