services:
    postgres:
        image: postgres
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-tasket}
            POSTGRES_USER: ${POSTGRES_PASSWORD:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
