name: Deploy
on:
    workflow_run:
        workflows: [ Build ]
        branches:
            - main
        types:
            - completed

jobs:
    docker:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        permissions:
            contents: read
            packages: write
        steps:
            -   uses: actions/checkout@v4

            -   name: Extract Version
                run: |
                    VERSION=$(grep "^tasketVersion=" gradle.properties | cut -d'=' -f2 | tr -d ' ')
                    echo "VERSION=$VERSION" >> $GITHUB_ENV

            -   name: Log in to GitHub Container Registry
                uses: docker/login-action@v2
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Build Docker Image
                run: docker build -t ghcr.io/${{ github.repository_owner }}/tasket:${{ env.VERSION }} .

            -   name: Push Docker Image
                run: docker push ghcr.io/${{ github.repository_owner }}/tasket:${{ env.VERSION }}

            -   name: Tag and Push Latest
                run: |
                    docker tag ghcr.io/${{ github.repository_owner }}/tasket:${{ env.VERSION }} ghcr.io/${{ github.repository_owner }}/tasket:latest
                    docker push ghcr.io/${{ github.repository_owner }}/tasket:latest
